### PR TITLE
Testing Refactor, New Documentaiton, & Cont Energy Xsec Config script

### PR DESCRIPTION
**Pull request by jpmorgan98**
This probably should have been multiple PRs but oh well.

# New features:
- Testing refactor: Adds osx64 testing target (in-conjunction with linux64), splits regression test into multiple runners to make it go faster! See issue #126 *all the same tests are running*
- Adding some new documentation to generally describe the contribution process to MC/DC
- Continuous energy config: Runs a separate bash script that can be individually launched. To run must be part of the cement center

There are no new dependence, physics, or CS back ends

### CODE REVIEW

**Comment by clemekay** [comment]
I cloned your branch and tried to install and get the following error:

> PackagesNotFoundError: The following packages are not available from current channels:
>   - ngsolve
>   - distinctipy
>
> Current channels:
> 
>   - https://repo.anaconda.com/pkgs/main/osx-arm64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/osx-arm64
>   - https://repo.anaconda.com/pkgs/r/noarch

Do those need to be installed from specific channels?

**Comment by clemekay** [comment]
Update: distinctipy needed the condaforge channel. For ngsolve, their available installations are osx-64, linux-64, and win-64; I've got an Apple M2 and would need osx-arm64 or noarch :/

**Comment by jpmorgan98** [comment]
So this new dependincy was actually added back in PR #109. Apple Sillicon M1 issues where known and discussed in issue #138. We actually don't need the parts of ngsolve that are incompatible so it still works. It just requires a pip install. I will change this in the install script.

**Comment by clemekay** [comment]
Gotcha, didn't think to check the visualizer thread. I also haven't been able to build ngsolve from their source instructions or forums, so I'm glad that's not necessary!

**Review by clemekay — APPROVED** [review]
Just commenting this here because I didn't realize we'd already known that ngsolve and distinctipy don't work via conda installation for Apple M1. The way the
`conda install package1 package2 ...`
command works, if any of the packages can't be found it voids the whole command and nothing installs. So having any packages in that line that end up being unavailable voids the whole install script!

**Pull request merged**
