### PR TITLE
Fixing capabilities on continuous energy mode

### PR DESCRIPTION
**Pull request by ilhamv**

### CODE REVIEW

**Comment by jpmorgan98** [comment]
Do we have any verification/regression tests for continuous energy?

**Comment by ilhamv** [comment]
Good point. But no, not yet. How should we deal with the data library in the GitHub workflow?

**Review by jpmorgan98 — APPROVED** [review]
These all look good and classify as bug fixes. Eventually we will need documentation and testing but we have to wait on those while we get info from the higher ups.

**Comment by jpmorgan98** [comment]
Pull in updates then merge the request!

**Comment by jpmorgan98** [comment]
Just to put this here--we are getting guidance from PSAAP on how best to do continuous energy transport with export control considerations

**Pull request merged**
